# Form implementation generated from reading ui file '/home/diablo76/Documents/GitHub/Ubuntu-Desktop-File/Assets/ui_files/ubuntu_desktop_cat1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 267)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 393, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 3, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 1, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 2, 1, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 4, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 2, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 0, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 0, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 3, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_4.setText(_translate("Form", "Education"))
        self.checkBox_8.setText(_translate("Form", "Office"))
        self.checkBox_5.setText(_translate("Form", "Game"))
        self.checkBox_7.setText(_translate("Form", "Network "))
        self.checkBox.setText(_translate("Form", "AudioVideo"))
        self.checkBox_11.setText(_translate("Form", "Building"))
        self.checkBox_12.setText(_translate("Form", "DesktopSettings"))
        self.checkBox_15.setText(_translate("Form", "Qt"))
        self.checkBox_2.setText(_translate("Form", "Audio"))
        self.checkBox_14.setText(_translate("Form", "TextEditor"))
        self.checkBox_3.setText(_translate("Form", "Development"))
        self.checkBox_6.setText(_translate("Form", "Graphics"))
        self.checkBox_10.setText(_translate("Form", "Utility"))
        self.checkBox_13.setText(_translate("Form", "FileTools"))
        self.checkBox_9.setText(_translate("Form", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
